version: "3.9"

volumes:
  db_data:
  app_media:
  app_static:

services:
  app:
    image: local/study
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_media:/app/media
      - app_static:/app/static_root
  nginx:
    image: nginx:1.21.4-alpine
    restart: on-failure
    volumes:
      - app_static:/static:ro
      - app_media:/media:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
  db:
    image: mariadb:10.7.1
    restart: on-failure
    volumes:
      - db_data:/var/lib/sqlite
    ports:
      - "3306:3306"
    env_file:
      - .env