# Generated by Django 4.0.5 on 2022-06-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название кафедры')),
            ],
            options={
                'verbose_name': 'кафедра',
                'verbose_name_plural': 'кафедры',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя преподавателя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('teams_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.teams', verbose_name='кафедра')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя студента')),
                ('middle_name', models.CharField(max_length=50, verbose_name='отчество студента')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия студента')),
                ('teams_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.teams', verbose_name='кафедра')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
            },
        ),
    ]
