# Generated by Django 4.0.5 on 2022-06-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='предмет')),
                ('text', models.TextField(verbose_name='поле для домашней работы')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/student', verbose_name='фотография студента'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/teacher', verbose_name='фотография преподавателя'),
        ),
        migrations.AddField(
            model_name='teams',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/teams', verbose_name='изображение кафедры'),
        ),
    ]
